### ISSUE TITLE
Allow string arguments to be specified without an array

### ISSUE THREAD

**Issue by rightaway** [hlefebvr/json-manipulation#1]
Would be a nice addition to allow `jsonOmit(object, 'a', 'b', 'c.d')` instead of needing to wrap them in an array. Because otherwise if you start with `jsonOmit(object, 'a')` and add a second argument, instead of simply adding the second argument you also need to wrap it in an array.

**Comment by hlefebvr** [comment]
Hello there ! 

Thank you for your suggestion, I have just released a new version (version 3.0) which takes into account your suggestion as well as enabling specific rows inside arrays to be touched. The other functionalities remain the same. 

From now then, you **have** to use `json-omit` like `omit(object, 'a', 'b', 'c')`, passing an array will result a failure. 

As well, the omit function is now exported inside an object, thus, use `const { omit } = require('json-omit')` to use it. The module exports as well a `clone` funciton which deeply clones an object passed as argument.
